#!/bin/bash

source ../../../utils/test_config.sh

# Check existence of passes
[ -f "$ARBOS_PASSES_DIR/libtest-parsing-call-args.$DYNLIB_EXT" ] || { echo >&2 "libunittest-parsing-call-args.$DYNLIB_EXT not found.  Aborting."; exit 1; }

clang -emit-llvm -o test.bc -g -c test.c
[ -f test.bc ] || { echo >&2 "Test Failed! Cannot generate LLVM bitcode.  Aborting."; exit 1; }

opt -load=$LLVM_PASSES_DIR/"$llvm_arbos_module" $LLVM_PASSES $PRE_ARBOS_PASSES -arbos -disable-output < test.bc > test.ar
[ -f test.ar ] || { echo >&2 "Test Failed! Cannot generate AR.  Aborting."; exit 1; }

# clang 4 does not give nice names to parameters
#arbos -load="$ARBOS_PASSES_DIR/libtest-parsing-call-args.$DYNLIB_EXT" -unittest-parsing-call-args < test.ar >/dev/null 2>&1 || { echo >&2 "Test Failed! Cannot parse test.ar"; exit 1; }

echo "Test Passed!"

rm *.bc *.ar
