#!/bin/bash

source ../../../../utils/test_config.sh

# test.bc generated using: clang -emit-llvm -o test.bc -g -c test.c
[ -f test.bc ] || { echo >&2 "Test Failed! LLVM bitcode unavailable.  Aborting."; exit 1; }

opt -load="$LLVM_PASSES_DIR/$llvm_arbos_module" $LLVM_PASSES $PRE_ARBOS_PASSES -arbos -disable-output < test.bc > test.ar
[ -f test.ar ] || { echo >&2 "Test Failed! Cannot generate AR.  Aborting."; exit 1; }

arbos -load="$ARBOS_PASSES_DIR/libtest-parsing-exit-nodes.$DYNLIB_EXT" -check-exit-nodes -L main -L bb6 -L bb3 -L null < test.ar >/dev/null 2>&1 || { echo >&2 "Test Failed! Cannot parse test.ar"; exit 1; }

echo "Test Passed!"

rm *.ar
