#!/bin/bash

source ../../../../utils/test_config.sh

# Check existence of passes
[ -f "$ARBOS_PASSES_DIR/libtest-parsing-src-lines-1.$DYNLIB_EXT" ] || { echo >&2 "unittest-parsing-src-lines-1.$DYNLIB_EXT not found.  Aborting."; exit 1; }

ikos-pp -ikospp-level=simple test.bc -o test.pp.bc

opt -load="$LLVM_PASSES_DIR/$llvm_arbos_module" -arbos -disable-output < test.pp.bc > test.ar
[ -f test.ar ] || { echo >&2 "Test Failed! Cannot generate AR.  Aborting."; exit 1; }

# clang does not give nice names to basic blocks and variables
#arbos -load="$ARBOS_PASSES_DIR/libtest-parsing-src-lines-1.$DYNLIB_EXT" -unittest-parsing-src-lines-1 < test.ar >/dev/null 2>&1 || { echo >&2 "Test Failed! Cannot parse test.ar"; exit 1; }

echo "Test Passed!"

rm test.pp.bc test.ar
